# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PI_G8_BeneficieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PI_G8_BeneficieApp
	pod 'Alamofire'
	pod 'IQKeyboardManagerSwift'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'GoogleSignIn'
	pod 'FBSDKLoginKit'
	# pod 'FirebaseUI'

end
